// @vitest-environment node
import {beforeEach,afterEach,describe,it,expect} from 'vitest';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {records,pendingRecords,importBatch} from './location-import-lib.mjs';

let db;
beforeEach(()=>{db=new DatabaseSync(':memory:');for(const name of ['0003_operations_preparation.sql','0004_system_settings.sql'])db.exec(readFileSync(new URL(`../migrations/${name}`,import.meta.url),'utf8'));});afterEach(()=>db.close());
function run(batch){db.exec('BEGIN');try{const result=batch.map(({sql,params})=>db.prepare(sql).run(...params));db.exec('COMMIT');return result;}catch(error){db.exec('ROLLBACK');throw error;}}
describe('central Asia test location import',()=>{
  it('publishes six countries and 28 cities with exact Chinese labels and audit records',()=>{const result=run(importBatch(0,records).batch);expect(result.every(row=>row.changes===1)).toBe(true);const rows=db.prepare('SELECT * FROM ops_settings ORDER BY kind,scope').all();expect(rows).toHaveLength(34);expect(rows.filter(row=>row.kind==='country')).toHaveLength(6);expect(rows.filter(row=>row.kind==='city')).toHaveLength(28);expect(rows.every(row=>row.status==='published'&&row.effective_at)).toBe(true);for(const record of records)expect(rows.find(row=>row.id===record.id)).toMatchObject({scope:record.scope,title:record.title,data_json:JSON.stringify(record.data)});expect(db.prepare('SELECT count(*) n FROM ops_events').get().n).toBe(34);expect(pendingRecords(rows)).toEqual([]);});
  it('stores Minsk under owner-confirmed Belarus',()=>{const minsk=records.find(row=>row.scope==='BY:Minsk');expect(minsk).toMatchObject({kind:'city',data:{countryCode:'BY',cityValue:'Minsk',nameZh:'明斯克'}});expect(records.find(row=>row.scope==='RU:Minsk')).toBeUndefined();run(importBatch(0,[minsk]).batch);expect(db.prepare("SELECT title FROM ops_settings WHERE scope='BY:Minsk'").get().title).toContain('BY');expect(db.prepare("SELECT reason FROM ops_events WHERE resource_id=?").get(minsk.id).reason).not.toContain('待业务确认');});
  it('is idempotent, rejects conflicts and rolls back incomplete batches',()=>{run(importBatch(0,records).batch);const rows=db.prepare('SELECT * FROM ops_settings').all();expect(pendingRecords(rows)).toEqual([]);expect(()=>pendingRecords([{...rows[0],data_json:'{}'},...rows.slice(1)])).toThrow('conflicts');expect(()=>pendingRecords([{...rows.find(row=>row.scope==='CN'),id:'conflicting-country-id'},...rows.filter(row=>row.scope!=='CN')])).toThrow('conflicts');expect(pendingRecords(rows.filter(row=>row.scope!=='CN'))).toHaveLength(1);const fresh=new DatabaseSync(':memory:');try{for(const name of ['0003_operations_preparation.sql','0004_system_settings.sql'])fresh.exec(readFileSync(new URL(`../migrations/${name}`,import.meta.url),'utf8'));const {batch}=importBatch(0,records);batch.push({sql:"INSERT INTO ops_settings(id,kind,scope,title,data_json,status,created_at,updated_at) VALUES('bad','invalid','bad','bad','{}','published','now','now')",params:[]});fresh.exec('BEGIN');expect(()=>{for(const item of batch)fresh.prepare(item.sql).run(...item.params);fresh.exec('COMMIT');}).toThrow();fresh.exec('ROLLBACK');expect(fresh.prepare('SELECT count(*) n FROM ops_settings').get().n).toBe(0);expect(fresh.prepare('SELECT revision FROM ops_meta').get().revision).toBe(0);}finally{fresh.close();}});
});
