function fieldToken(csrf: string) {
  if (!/^[a-f0-9]{64}$/.test(csrf)) throw new Error("Invalid CSRF token");
  return `<input type="hidden" name="csrf" value="${csrf}">`;
}
function page(title: string, content: string, controls = '<span class="private-label">独立管理入口 · Administration</span>') {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Moviloq · ${title}</title><link rel="stylesheet" href="/admin.css"></head><body><header><a class="brand" href="https://moviloq.com"><span class="mark">M</span>moviloq<span class="brand-label">ADMIN</span></a>${controls}</header>${content}<footer><span>Moviloq · Frankfurt am Main</span><span>管理入口 / Administration</span></footer></body></html>`;
}
const messages: Record<string, string> = {
  invalid: "账号或密码不正确。 / Incorrect account or password.",
  limited: "尝试次数过多，请在 15 分钟后重试。 / Too many attempts. Please retry in 15 minutes.",
  changed: "密码已更新，请重新登录。 / Password updated. Please sign in again.",
  requirements: "两次新密码需一致，长度为 15–128 个字符。 / Use matching passwords of 15–128 characters.",
  different: "新密码不能与当前密码相同。 / Choose a different password."
};
function message(code: string) { return messages[code] ? `<p class="notice" role="alert">${messages[code]}</p>` : ""; }
export function loginHtml(csrf: string, code = "") {
  return page("管理员登录", `<main class="login-layout"><section><div class="eyebrow">MOVILOQ / ADMINISTRATION</div><h1>每一程服务，<br>从这里管理。</h1><p class="intro">欢迎回到 Moviloq。使用你的管理账号和密码登录。</p><p class="english" lang="en">Welcome back. Sign in with your administrator account and password.</p><div class="login-note"><span class="status">平台管理 · Platform administration</span><p>此入口仅供获授权的管理员使用。<br><span lang="en">For authorized administrators only.</span></p></div><a class="return-link" href="https://moviloq.com">返回客户网站 / Customer website →</a></section><section class="form-card" aria-labelledby="login-title"><div class="eyebrow">WELCOME BACK</div><h2 id="login-title">管理员登录</h2><p class="english" lang="en">Administrator sign-in</p>${message(code)}<form method="post" action="/login">${fieldToken(csrf)}<label for="username">账号 / Account</label><input id="username" name="username" type="text" autocomplete="username" autocapitalize="none" spellcheck="false" maxlength="254" placeholder="用户名或邮箱 / Username or email" required><label for="password">密码 / Password</label><input id="password" name="password" type="password" autocomplete="current-password" maxlength="512" required><button class="primary" type="submit">登录 / Sign in <span aria-hidden="true">→</span></button></form><p class="form-help">忘记密码？请联系平台所有者重置。<br><span lang="en">Forgot your password? Contact the platform owner.</span></p></section></main>`);
}
export function passwordHtml(csrf: string, code = "") {
  return page("修改密码", `<main class="password-layout"><div class="eyebrow">ACCOUNT / SECURITY</div><h1>修改密码</h1><p class="intro">更改后，所有设备的现有登录都会退出。</p><p class="english" lang="en">Changing your password signs out all existing sessions.</p><section class="form-card">${message(code)}<form method="post" action="/password">${fieldToken(csrf)}<label for="current">当前密码 / Current password</label><input id="current" name="current" type="password" autocomplete="current-password" maxlength="512" required><label for="password">新密码 / New password</label><input id="password" name="password" type="password" autocomplete="new-password" minlength="15" maxlength="128" aria-describedby="password-help" required><p id="password-help" class="form-help">15–128 个字符，可使用长句，区分大小写。<br><span lang="en">15–128 characters. Passphrases are welcome.</span></p><label for="confirmation">确认新密码 / Confirm new password</label><input id="confirmation" name="confirmation" type="password" autocomplete="new-password" minlength="15" maxlength="128" required><button class="primary" type="submit">保存新密码 / Save password →</button></form></section><a class="return-link" href="/">返回工作台 / Back to workspace</a></main>`);
}
export function readyHtml(csrf: string) {
  return page("管理工作台", `<main><div class="eyebrow">MOVILOQ / ADMINISTRATION</div><h1>欢迎进入<br>管理工作台。</h1><p class="intro">管理员身份验证已通过。这里是后台的安全状态页，业务管理模块仍在开发中。</p><p class="english" lang="en">You are signed in. Business management is not enabled yet.</p><section class="access-card" aria-labelledby="access-title"><div class="lock" aria-hidden="true">&#128274;</div><div><span class="status">账号密码登录 · Password sign-in</span><h2 id="access-title">安全访问已建立</h2><p>当前角色：平台所有者。已开放安全状态查看和修改密码，不开放客户资料、订单、司机、车队或资金操作。</p><p class="english" lang="en">Role: platform owner. Readiness and password settings only. No customer, order, partner or payment operations.</p><a class="return-link" href="/password">修改密码 / Change password →</a></div></section><div class="boundaries"><div><span>01 / PLATFORM</span><h3>平台运营后台</h3><p>审核中心与业务审计待开发<br><span lang="en">Reviews and business audit: planned</span></p></div><div><span>02 / DRIVERS</span><h3>司机端</h3><p>入驻、资质审核与接单待开发<br><span lang="en">Onboarding and delivery jobs: planned</span></p></div><div><span>03 / FLEETS</span><h3>车队端</h3><p>成员、车辆与内部调度待开发<br><span lang="en">Members, vehicles and dispatch: planned</span></p></div></div><p class="english">当前仅连接独立的管理员认证数据库，不连接客户业务数据库，不展示模拟运营数据。<br><span lang="en">Only the separate admin authentication database is connected. No business data or fabricated metrics.</span></p></main>`, `<form method="post" action="/logout">${fieldToken(csrf)}<button class="status signout" type="submit">退出 / Sign out</button></form>`);
}
export const unavailableHtml = page("登录暂不可用", '<main><div class="eyebrow">MOVILOQ / ADMINISTRATION</div><h1>登录暂不可用</h1><p>管理账号正在配置，请稍后再试。</p><p lang="en">Administrator sign-in is being configured. Please try again later.</p></main>');
const baseCss = `:root{font-family:Inter,"Segoe UI","Microsoft YaHei",sans-serif;color:#163a34;background:#f5f5ef;font-synthesis:none}*{box-sizing:border-box}body{margin:0;min-width:320px}a{color:inherit;text-decoration:none}header,footer{max-width:1160px;margin:auto;padding:28px 32px;display:flex;align-items:center;justify-content:space-between;gap:20px}header{border-bottom:1px solid #dce2d7}.brand{display:flex;align-items:center;gap:12px;font-size:25px;font-weight:800;letter-spacing:-1px}.mark{display:grid;place-items:center;width:36px;height:36px;background:#f56535;border-radius:10px 10px 10px 3px;color:white;font-size:19px;letter-spacing:0}.brand-label{font-size:10px;letter-spacing:2px;border-left:1px solid #bdc9bd;padding-left:13px;margin-left:5px;color:#6b7c72}.private-label{font-size:12px;color:#627369}main{max-width:1010px;margin:auto;padding:80px 32px}.eyebrow{font-size:11px;letter-spacing:2px;font-weight:750;color:#c7502d}h1{font-size:clamp(36px,5vw,58px);line-height:1.3;letter-spacing:-2px;margin:20px 0 26px}p{line-height:1.8}.intro{max-width:660px;font-size:17px;color:#52685d}.english{max-width:660px;color:#65796d;font-size:13px}.access-card{display:flex;align-items:flex-start;gap:22px;background:#fff;border:1px solid #dce4d8;border-radius:18px;padding:30px;margin:38px 0;box-shadow:0 15px 40px #223c2410}.lock{display:grid;place-items:center;flex-shrink:0;width:50px;height:50px;background:#fff2e8;border-radius:14px;font-size:22px}.status{display:inline-block;background:#fff2e8;color:#aa492b;padding:6px 10px;border-radius:7px;font-size:11px;font-weight:700}h2{font-size:22px;margin:17px 0 10px}.access-card p{font-size:14px;color:#566a5c;margin:8px 0}.access-card .english{font-size:12px}.boundaries{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:28px}.boundaries>div{border-top:1px solid #cedacd;padding-top:18px}.boundaries>div>span{font-size:11px;color:#7b8c7e}h3{font-size:15px;font-weight:650;margin:13px 0}.boundaries p{font-size:12px;color:#526a5b}.boundaries p span{font-size:11px;color:#657a6b}.return-link{display:inline-block;margin-top:38px;font-size:13px;text-decoration:underline;text-underline-offset:5px}.return-link:focus-visible{outline:2px solid #f56535;outline-offset:6px}footer{color:#657569;font-size:11px;border-top:1px solid #dce2d7}@media(max-width:600px){header,footer{padding:22px 20px}.private-label{display:none}main{padding:48px 20px}.access-card{padding:22px;gap:15px;flex-direction:column}.boundaries{grid-template-columns:1fr;gap:18px}h1{letter-spacing:-1px}footer{align-items:flex-start;flex-direction:column;gap:10px}}`;
export const adminCss = baseCss + `button,input{font:inherit}button{cursor:pointer}.login-layout{max-width:1160px;display:grid;grid-template-columns:1fr 420px;gap:70px;align-items:center;min-height:75vh}.form-card{padding:32px;background:white;border:1px solid #dce4d8;border-radius:18px;box-shadow:0 15px 40px #223c2410;min-width:0}.form-card h2{margin:14px 0 4px;font-size:26px}.form-card label{display:block;font-size:13px;font-weight:650;margin:25px 0 9px}.form-card input{display:block;width:100%;padding:13px 14px;border:1px solid #bbc9bd;background:#fcfdfb;border-radius:9px;color:#163a34;min-height:48px;font-size:16px}.form-card input[type=hidden]{display:none}.primary{display:flex;justify-content:space-between;align-items:center;gap:8px;width:100%;margin-top:28px;padding:15px 18px;border:0;border-radius:9px;background:#c7502d;color:white;font-weight:650;font-size:14px;min-height:50px}.primary:hover{background:#a84124}.form-help{font-size:12px;color:#65796d;margin:18px 0 0}.notice{padding:12px 14px;background:#fff2e8;border-left:3px solid #c7502d;border-radius:5px;font-size:13px;overflow-wrap:anywhere}.login-note{margin-top:32px}.login-note p{font-size:12px;color:#65796d}.password-layout{max-width:650px}.password-layout h1{font-size:40px}.password-layout .form-card{margin-top:30px}.signout{border:1px solid #d7b9a4;min-height:42px}.access-card .return-link{margin-top:10px}:is(a,button,input):focus-visible{outline:3px solid #c7502d;outline-offset:4px}@media(max-width:900px){.login-layout{gap:35px;grid-template-columns:1fr 380px}.login-layout h1{font-size:40px}}@media(max-width:700px){.login-layout{grid-template-columns:1fr;gap:30px;min-height:0}.login-layout h1{font-size:36px}.login-note{display:none}.login-layout .return-link{margin-top:12px}.form-card{padding:25px 22px}.brand-label{display:none}header{gap:8px}.brand{font-size:22px}.password-layout h1{font-size:34px}}\n`;
