export const adminEntryHtml = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Moviloq · 管理后台</title><link rel="stylesheet" href="/admin.css"></head>
<body><header><a class="brand" href="https://moviloq.com"><span class="mark">M</span>moviloq<span class="brand-label">ADMIN</span></a><span class="private-label">受限管理入口 · Restricted</span></header>
<main><div class="eyebrow">MOVILOQ / ADMINISTRATION</div><h1>管理业务，<br>从安全访问开始。</h1><p class="intro">平台运营的独立入口。管理员身份验证与权限配置完成前，管理功能保持关闭。</p><p class="english" lang="en">Your administration workspace. Management access remains disabled until secure sign-in and permissions are configured.</p>
<section class="access-card" aria-labelledby="access-title"><div class="lock" aria-hidden="true">&#128274;</div><div><span class="status">尚未启用 · Not enabled</span><h2 id="access-title">管理员登录待开通</h2><p>当前页面不连接业务数据库，不展示客户、订单、司机或车队资料。这里不是开放注册入口。</p><p class="english" lang="en">No business data is connected or displayed. Administrator registration is not public.</p></div></section>
<div class="boundaries"><div><span>01</span><h3>专属管理域名</h3><p>admin.moviloq.com<br><span lang="en">Separate administration endpoint</span></p></div><div><span>02</span><h3>管理员身份验证</h3><p>指定账号授权与多因素认证待配置<br><span lang="en">Allowlisted access and MFA pending</span></p></div><div><span>03</span><h3>独立角色权限</h3><p>平台、司机与车队分开授权<br><span lang="en">Platform and partner roles stay separate</span></p></div></div>
<a class="return-link" href="https://moviloq.com">返回客户网站 <span lang="en">/ Customer website →</span></a></main><footer><span>Moviloq · Frankfurt am Main</span><span>Development / Access not enabled</span></footer></body></html>`;

export const adminEntryCss = `:root{font-family:Inter,"Segoe UI","Microsoft YaHei",sans-serif;color:#163a34;background:#f5f5ef;font-synthesis:none}*{box-sizing:border-box}body{margin:0;min-width:320px}a{color:inherit;text-decoration:none}header,footer{max-width:1160px;margin:auto;padding:28px 32px;display:flex;align-items:center;justify-content:space-between;gap:20px}header{border-bottom:1px solid #dce2d7}.brand{display:flex;align-items:center;gap:12px;font-size:25px;font-weight:800;letter-spacing:-1px}.mark{display:grid;place-items:center;width:36px;height:36px;background:#f56535;border-radius:10px 10px 10px 3px;color:white;font-size:19px;letter-spacing:0}.brand-label{font-size:10px;letter-spacing:2px;border-left:1px solid #bdc9bd;padding-left:13px;margin-left:5px;color:#6b7c72}.private-label{font-size:12px;color:#627369}main{max-width:1010px;margin:auto;padding:80px 32px}.eyebrow{font-size:11px;letter-spacing:2px;font-weight:750;color:#c7502d}h1{font-size:clamp(36px,5vw,58px);line-height:1.3;letter-spacing:-2px;margin:20px 0 26px}p{line-height:1.8}.intro{max-width:660px;font-size:17px;color:#52685d}.english{max-width:660px;color:#65796d;font-size:13px}.access-card{display:flex;align-items:flex-start;gap:22px;background:#fff;border:1px solid #dce4d8;border-radius:18px;padding:30px;margin:38px 0;box-shadow:0 15px 40px #223c2410}.lock{display:grid;place-items:center;flex-shrink:0;width:50px;height:50px;background:#fff2e8;border-radius:14px;font-size:22px}.status{display:inline-block;background:#fff2e8;color:#aa492b;padding:6px 10px;border-radius:7px;font-size:11px;font-weight:700}h2{font-size:22px;margin:17px 0 10px}.access-card p{font-size:14px;color:#566a5c;margin:8px 0}.access-card .english{font-size:12px}.boundaries{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:28px}.boundaries>div{border-top:1px solid #cedacd;padding-top:18px}.boundaries>div>span{font-size:11px;color:#7b8c7e}h3{font-size:15px;font-weight:650;margin:13px 0}.boundaries p{font-size:12px;color:#526a5b}.boundaries p span{font-size:11px;color:#657a6b}.return-link{display:inline-block;margin-top:38px;font-size:13px;text-decoration:underline;text-underline-offset:5px}.return-link:focus-visible{outline:2px solid #f56535;outline-offset:6px}footer{color:#657569;font-size:11px;border-top:1px solid #dce2d7}@media(max-width:600px){header,footer{padding:22px 20px}.private-label{display:none}main{padding:48px 20px}.access-card{padding:22px;gap:15px;flex-direction:column}.boundaries{grid-template-columns:1fr;gap:18px}h1{letter-spacing:-1px}footer{align-items:flex-start;flex-direction:column;gap:10px}}`;
