import { createHash } from "node:crypto";
import { h, t, type View } from "./ops-view";

const script = `(()=>{const dialog=document.querySelector('#settings-dialog');if(!dialog||!dialog.showModal)return;const content=dialog.querySelector('[data-settings-content]');const error=dialog.querySelector('[role=alert]');let opener,busy=false,controller;
const showError=()=>{error.hidden=false;};
async function load(url){controller?.abort();controller=new AbortController();error.hidden=true;content.textContent=dialog.dataset.loading;try{const response=await fetch(url,{signal:controller.signal});if(!response.ok||new URL(response.url).pathname==='/login')throw Error();const doc=new DOMParser().parseFromString(await response.text(),'text/html');const main=doc.querySelector('.workspace main');if(!main)throw Error();content.replaceChildren(...main.childNodes);content.querySelector('input:not([type=hidden]),select,textarea')?.focus();}catch(e){if(e.name!=='AbortError')showError();}}
document.addEventListener('click',e=>{const link=e.target.closest('a[data-settings-dialog]');if(!link||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();opener=link;dialog.showModal();load(link.href);});
dialog.querySelector('[data-settings-close]').addEventListener('click',()=>{if(!busy)dialog.close();});dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('close',()=>{controller?.abort();content.replaceChildren();opener?.focus();});
dialog.addEventListener('submit',async e=>{const form=e.target;if(!(form instanceof HTMLFormElement))return;e.preventDefault();if(busy)return;if(form.method.toLowerCase()==='get'){const url=new URL(form.action);url.search=new URLSearchParams(new FormData(form)).toString();return load(url);}busy=true;error.hidden=true;const buttons=[...dialog.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{const response=await fetch(form.action,{method:'POST',body:new URLSearchParams(new FormData(form))});if(!response.ok||new URL(response.url).pathname==='/login')throw Error();if(response.redirected){window.location.assign(response.url);}else{const doc=new DOMParser().parseFromString(await response.text(),'text/html');const main=doc.querySelector('.workspace main');if(!main)throw Error();content.replaceChildren(...main.childNodes);}}catch{showError();}finally{busy=false;buttons.forEach(b=>b.disabled=false);}});})();`;
export const settingsDialogHash = `sha256-${createHash("sha256").update(script).digest("base64")}`;
export function settingsDialog(v: View) {
  return `<dialog id="settings-dialog" aria-labelledby="settings-dialog-title" data-loading="${h(t(v,["正在加载…","Loading…"]))}"><div class="settings-dialog-head"><h2 id="settings-dialog-title">${h(t(v,["配置草稿","Configuration draft"]))}</h2><button type="button" data-settings-close>${h(t(v,["关闭","Close"]))}</button></div><p role="alert" hidden>${h(t(v,["操作未完成。请检查必填内容、国家城市代码及权限；如有版本冲突或网络异常，请刷新核对后再提交。已填写内容不会被清空。","Request incomplete. Check required fields, location identifiers and permissions. For version conflicts or network errors, refresh and verify before retrying. Your input is retained."]))}</p><div data-settings-content></div></dialog><script>${script}</script>`;
}
export const settingsDialogCss = `#settings-dialog{width:min(900px,94vw);max-height:90vh;overflow:auto;border:0;border-radius:14px;padding:24px;color:#173e38}#settings-dialog::backdrop{background:#102c26aa}.settings-dialog-head{display:flex;align-items:center;justify-content:space-between;gap:20px}#settings-dialog [role=alert]{background:#fff0e7;padding:16px}#settings-dialog .page-heading{margin-top:20px}.settings-tabs{display:flex;gap:18px;padding:16px;flex-wrap:wrap}`;
